Repository Gods-Of-ACM/frontEnd, pull requests merged in 2018-04, with the labels that each got.

#35 Merging Messages Branch/ Removed Vestigial Code/ Basic Tests
  app/components/BigBtn1/index.js
  app/components/BigBtn1/tests/index.test.js
  app/components/Button1/index.js
  app/components/PageHeader/index.js
  app/components/PageHeader/messages.js
  app/components/PageHeader/tests/index.test.js
  app/containers/App/constants.js
  app/containers/EntriesPage/index.js
  app/containers/EntriesPage/messages.js
  app/containers/HomePage/index.js
  app/containers/HomePage/messages.js
  app/containers/HomePage/tests/index.test.js
  app/containers/Login/index.js
  app/containers/Login/messages.js
  app/containers/ManageAccounts/index.js
  app/containers/ManageAccounts/messages.js
  app/containers/NotFoundPage/index.js
  app/containers/NotFoundPage/messages.js
  app/containers/Profile/index.js
  app/containers/Profile/messages.js
  app/containers/Registration/index.js
  app/containers/Registration/messages.js
  app/containers/ViewDBPage/index.js
  app/containers/ViewDBPage/messages.js
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement

#40 Debian fix
  .travis.yml
  =21.0.0
  README.md
  yarn.lock
Labels: bug

#46 Search Bar
  app/components/SearchBar/Loadable.js
  app/components/SearchBar/index.js
  app/components/SearchBar/messages.js
  app/components/SearchBar/tests/index.test.js
  app/themes.js
Labels: UI, enhancement

#49 Added bootstrap to the project :)
  app/app.js
  package-lock.json
  package.json
  vendor/css/bootstrap.min.css
  vendor/fonts/glyphicons-halflings-regular.eot
  vendor/fonts/glyphicons-halflings-regular.svg
  vendor/fonts/glyphicons-halflings-regular.ttf
  vendor/fonts/glyphicons-halflings-regular.woff
  vendor/fonts/glyphicons-halflings-regular.woff2
Labels: UI, enhancement, good first issue

#51 Bootstrapify
  app/app.js
  app/containers/App/index.js
  app/containers/Footer/index.js
  app/containers/Footer/messages.js
  app/containers/HomePage/index.js
  app/containers/HomePage/messages.js
  app/containers/NavBar/index.js
  app/global-styles.js
  app/images/CheMoa_Transparent.png
  app/themes.js
Labels: UI, enhancement

#55 Added the helper to handle construction of advanced query
  app/utils/advancedQuery.js
Labels: enhancement
